name: gds

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  gds:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: build gds
        uses: TinyTapeout/tt-gds-action@v1
        with:
          clock_period: "20.0" # 50 MHz
          json_path: "info.yaml"
